spring:
  application:
    name: messaging

  kafka:
    bootstrap-servers: ["localhost:29092"]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
