spring:
  application:
    name: batch

  kafka:
    bootstrap-servers: ["localhost:29092"]

  datasource:
    url: jdbc:mysql://localhost:13306/push
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
